### ISSUE TITLE
pear install doc.php.net/phd dos not work

### ISSUE THREAD

**Issue by winstonDeGreef** [php/phd#61] opened 2021-11-25 18:43 UTC
`pear install doc.php.net/phd` produces the following error:
```
No releases available for package "doc.php.net/phd"
install failed
```
Instead of installing phD.

**Comment by salathe** [comment] 2021-11-26 15:11
The above command is working for me for several different setups in differing locations, so I don't think there's a problem with the server; at least, right now.

Has the problem persisted?  Are you able to fetch the package listing at http://doc.php.net/rest/r/phd/allreleases2.xml (e.g. with `curl`, `wget`, etc.) from wherever you ran the `pear install` command?

**Comment by philip** [comment] 2022-01-26 22:55
This worked fine for me too; also you can see what `pear channel-info doc.php.net` says.

Closing this issue, feel free to reopen @winstonDeGreef if the problem is still present.

In reality the current doc.php.net/phd version is old and shouldn't be used to render php.net documentation; the phd code in git works best as it contains a lot of changes since 2018.

**Closed by philip** 2022-01-26 22:55 UTC
